### ISSUE TITLE
sheet-to-JSON empty payload

### ISSUE THREAD

**Issue by ecymb1** [sakai-to/node-red-contrib-spreadsheet-in#12]
Hi everyone,

I was wondering if there is an issue with the latest (Node-Red) update? My flow was working just fine before it. When I enter the range for the sheet-to-JSON node, it returns an empty payload. When I leave it empty (import all content), it works just fine by returning the entire spreadsheet as a JSON. Could someone please help?

Node.js Version: V14.19.0
Node-Red Version: V2.2.2

Flow:
![flow](https://user-images.githubusercontent.com/71962389/158056671-3fcc72ab-10a3-4bd1-beae-6de063e94be5.png)

Empty Range:
![Pic working](https://user-images.githubusercontent.com/71962389/158056686-8dd910b8-ad6d-42f4-828c-162689c01187.png)

Selected Range:
![pic not-working](https://user-images.githubusercontent.com/71962389/158056683-381acbef-6eb3-4c06-b79a-a5d368198a6e.png)

My Spreadsheet:
[SunEarthTools_AnnualSunPath_2022_1646659240235.xls](https://github.com/sakai-to/node-red-contrib-spreadsheet-in/files/8239388/SunEarthTools_AnnualSunPath_2022_1646659240235.xls)
:

Any (and all) help would be appreciated.

**Comment by ecymb1** [comment]
Hi @sakai-to,

I noticed something new, i found the same problem in the cell node. 
If the value is chosen, an empty payload is returned. If it's left empty, we get the entire spreadsheet in the payload.

**Comment by sakai-to** [comment]
Hi @ecymb1, thank you for the report. I could reproduce this issue on my computer. Looking at your spreadsheet, it doesn't seem to the correct spreadsheet. I believe it is a broken HTML because of missing <tr> start tags except the first row. Would you please correct your spreadsheet and try your flow again?

**Comment by ecymb1** [comment]
Hi @sakai-to,
You were right, it was an issue with the spreadsheet. I was able to get the flow running by correcting the spreadsheet.
Thanks for your generous time & guidance.
