### ISSUE TITLE
selectAddress or selectRange

### ISSUE THREAD

**Issue by DozoG** [sakai-to/node-red-contrib-spreadsheet-in#14]
Hi,

I can't figure out how to use the "optional properties" in the cell-node and the sheet-to-Json-node.

I have the example working but only with the Cell-address field filled in with literally A2 (for example)
and the Range field filled with literally A1:F2 (for example)
The input in both cases is the output of Sheet-node.

But this is not very flexible. I would like to use another node to select which cell on that sheet or what range on that sheet is converted to the payload object.

What do I fill in in the Cell-address field of the Cell-Node?
Where or how do I specify which cell I am looking for ?

Sorry if it should be very obvious, I am relatively new to node-red

Thanks, Oscar

**Comment by DozoG** [comment]
Some additional:

I have looked through the Closed Issues, and there is one that seems somewhat related.

#3 Jomel Jan 2019:
"As per the node documentation you can supply the name fo [of] the sheet to be selected in the sheet node either via the node prop or via incoming message prop. "

I am guessing message prop is short for message property, but it doesn't hint at what property or how to set it.
I have tried (several spellings of) "cellAddress" in different formats (J-Expression, string) in a change node, and then having the same name in the celladdress field of the Cell-Node.  It always comes back with invalid cell address.

**Comment by sakai-to** [comment]
@DozoG you can specify a cell address or a sheet range by using `selectAddress` or `selectRange` property of `msg` object. For example, to get A1 value, you put a `change` node between a `sheet` node and a `cell` node and set `A1` to `msg.selectAddress` in the `change` node. Note that when using these propeties, the cell address property on the `cell` node and the sheet range property on the `sheet to json` node should be left empty.

![image](https://user-images.githubusercontent.com/2355352/219925001-d067e4a6-00e9-4d28-a245-d40a18ea61e3.png)

**Comment by DozoG** [comment]
Thank you so much. This works for me. 

I was missing the correct property "selectAddress"
I swear I (thought I ) had tried exactly that. But obviously not.

Thanks again, I learned something.
