### ISSUE TITLE
sheet node requires sheet name prop even though you can supply it via message prop

### ISSUE THREAD

**Issue by jomel** [sakai-to/node-red-contrib-spreadsheet-in#3]
As per the node documentation you can supply the name fo the sheet to be selected in the sheet node either via the node prop or via incoming message prop.

However if you try to use message prop (& ommit the node prop) the editor complains that the node is not set up correctly. 
![image](https://user-images.githubusercontent.com/3426561/50591211-4ce51980-0e86-11e9-94aa-1af2f841e7e8.png)

I believe this is because the properties of the node are set to be required for this prop.
![image](https://user-images.githubusercontent.com/3426561/50591236-6c7c4200-0e86-11e9-9f17-469849b3d1a2.png)

Could you please update [this line](https://github.com/sakai-to/node-red-contrib-spreadsheet-in/blob/1739cf8d9523ac3f21b808c34e8ff8d57b2ecf89/sheet.html#L7)

**Comment by sakai-to** [comment]
jomel, thank you for the report and I'm sorry for delay of my reply.
I was be able to reproduce the issue and resolve it by changing the line as you pointed out. I am changing the line and will publish it as soon as possible.
