### ISSUE TITLE
Some excel files can not be read

### ISSUE THREAD

**Issue by s1r-J** [sakai-to/node-red-contrib-spreadsheet-in#4]
I am getting below error message when some excel files are read in book node.

I do not know why this happens.
However I upgrade xlsx@0.11.2 to 0.14.1(latest), it is solved.

```
<path>\.node-red\node_modules\xlsx\xlsx.js:17214
        } catch(e) { if(opts.WTF) throw e; }
                                  ^

TypeError: Cannot read property 'length' of undefined
    at isgeneral (<path>\.node-red\node_modules\xlsx\xl
sx.js:125:49)
    at Object.format (<path>\.node-red\node_modules\xls
x\xlsx.js:943:5)
    at safe_format (<path>\.node-red\node_modules\xlsx\
xlsx.js:10760:18)
    at parse_ws_xml_data (<path>\.node-red\node_modules
\xlsx\xlsx.js:11146:4)
    at parse_ws_xml (<path>\.node-red\node_modules\xlsx
\xlsx.js:10819:11)
    at parse_ws (<path>\.node-red\node_modules\xlsx\xls
x.js:12917:9)
    at safe_parse_sheet (<path>\.node-red\node_modules\
xlsx\xlsx.js:17199:32)
    at parse_zip (<path>\.node-red\node_modules\xlsx\xl
sx.js:17320:3)
    at read_zip (<path>\.node-red\node_modules\xlsx\xls
x.js:17537:9)
    at Object.readSync [as read] (<path>\.node-red\node
_modules\xlsx\xlsx.js:17584:68)
```

**Comment by sakai-to** [comment]
@s1r-J , thanks for your report. Could you please provide the excel files in order to reproduce this issue? I would like to investigate the root cause and decide whether it is needed to update the dependency for xlsx or not.

**Comment by s1r-J** [comment]
For sercurity reasons, I cannot upload the original file. So I wanted to remove personal information.

Excel 2016
[date.xlsx](https://github.com/sakai-to/node-red-contrib-spreadsheet-in/files/2969621/date.xlsx)

1. Write `2018/08/01` in A1 cell
1. Select `表示形式` - `ユーザー定義` - `yyyy"年"m"月"`
1. Save a file and start flow in Node-RED

**Comment by sakai-to** [comment]
Thank you for the information. I could reproduce this issue with them and it could be solved as you said. I will change the dependency of xlsx vesion.

**Comment by Chieftl** [comment]
I have similar bug, xlsx file can be read, error is showing
`"Error: Byte Order: Expected feff saw 0000"`

It's looks like xlsx file have old format, but I am testing this file with last version of xlsx npm package & it's working as well
```
const XLSX = require('xlsx')

var workbook = XLSX.readFile('test.xlsx')
const sheet = workbook.Sheets[workbook.SheetNames[0]]
var csvData = XLSX.utils.sheet_to_csv(sheet)

console.log(csvData)
```

Could you please take a look at what the problem is?
May be updating to last version of xlsx package may fix this.
Problem file attached.
[test.xlsx](https://github.com/sakai-to/node-red-contrib-spreadsheet-in/files/5919801/test.xlsx)

**Comment by sakai-to** [comment]
@Chieftl Thank you for the report and sorry for my late reply. I got the same error with your test.xlsx file. I will check this issues soon.

**Comment by alfaz151** [comment]
#18
