### ISSUE TITLE
Help implementing the code

### ISSUE THREAD

**Issue by JASpareY** [sakai-to/node-red-contrib-spreadsheet-in#5]
I am attempting to use this tool to parse specific spreadsheet data and display on a dashboard.  

I uploaded the code through NPM and the clipboard but the excel elements in the flow are not recognized (unknown: book) (unknown: sheet) (unknown: cell) (unknown: sheet-to-json).  I am very new to code red, any help is appreciated.

**Comment by sakai-to** [comment]
@JASpareY , I think your situation is that you imported the example flow before adding the nodes of this package into your Node-RED. Once you add this package in accordance with [Node-RED Documentation](https://nodered.org/docs/getting-started/adding-nodes), then the nodes shown as unknown will be available.

**Comment by JASpareY** [comment]
I was having some issues with NPM which is why it wasn't loading properly.  Thanks for the quick response.  I have resolved the issues with NPM and have uploaded this code.  Really appreciate the support!
